### ISSUE TITLE
Не создается столбец share

### ISSUE THREAD

**Issue by Gnucheva** [Gnucheva/NMedia#8]
#### Шаги по воспроизведению :
1. Запустить приложение Run app на эмуляторе.

#### Ожидаемый результат

Создание COLUMN_SHARE , COLUMN_VIEWS , COLUMN_VIDEO 

#### Фактический результат

Ошибка создания столбца : E/SQLiteLog: (1) no such column: share

#### Программное окружение

* Windows 10Pro , 64bit , версия 20H2, сборка 19042.928
* Java 11.0.7  2020-04-14

#### Stack trace 

02/21 12:57:14: Launching 'app' on Nexus 5X API 27.
App restart successful without requiring a re-install.
$ adb shell am start -n "ru.netology.nmedia/ru.netology.nmedia.activity.AppActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 2303 on device 'Nexus_5X_API_27 [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/zygote: Late-enabling -Xcheck:jni
W/zygote: Unexpected CPU variant for X86 using defaults: x86
E/SQLiteLog: (1) no such column: share
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.netology.nmedia, PID: 2303
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.netology.nmedia/ru.netology.nmedia.activity.AppActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class fragment
     Caused by: java.lang.RuntimeException: Cannot create an instance of class ru.netology.nmedia.viewmodel.PostViewModel
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:236)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:169)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:44)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:31)
        at ru.netology.nmedia.activity.FeedFragment.getViewModel(FeedFragment.kt:24)
        at ru.netology.nmedia.activity.FeedFragment.onCreateView(FeedFragment.kt:94)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
        at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:394)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:260)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:142)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:295)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:274)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:324)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:249)
        at ru.netology.nmedia.activity.AppActivity.onCreate(AppActivity.kt:17)
        at android.app.Activity.performCreate(Activity.java:7009)
E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:228)
        	... 44 more
     Caused by: android.database.sqlite.SQLiteException: no such column: share (code 1): , while compiling: SELECT id, author, content, published, likedByMe, likes, share, views, video FROM posts ORDER BY id DESC
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:890)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:501)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1392)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1239)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1110)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1278)
        at ru.netology.nmedia.dao.PostDaoImpl.getAll(PostDaoImpl.kt:52)
        at ru.netology.nmedia.repository.PostRepositorySQLiteImpl.<init>(PostRepositorySQLiteImpl.kt:16)
        at ru.netology.nmedia.viewmodel.PostViewModel.<init>(PostViewModel.kt:23)
        	... 47 more

#### Скриншоты

![NMedia – PostDaoImpl kt  NMedia app  2022-02-21 13](https://user-images.githubusercontent.com/63240341/154937121-4e38c077-1186-47d6-bf28-41a476e7583a.png)

**Comment by Gnucheva** [comment]
Удалила database
